apiVersion: apps/v1
kind: Deployment
metadata:
  name: apiclinhares
  namespace: hiperdev
spec:
  selector:
    matchLabels:
      app: apiclinhares
  template:
    metadata:
      labels:
        app: apiclinhares
    spec:
      containers:
      - name: apiclinhares
        image: hiperdevcr.azurecr.io/apiclinhares
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
