apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-Clinhares
  namespace: hiperdev
spec:
  selector:
    matchLabels:
      app: api-Clinhares
  template:
    metadata:
      labels:
        app: api-Clinhares
    spec:
      containers:
      - name: api-Clinhares
        image: hiperdevcr.azurecr.io/hiperdev
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
